trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: eco Build First Job
  - job: FirstJob
    steps:
    - bash: eco Build Second Job
- stage: DevDeploy
  jobs:
  - job: DevJob
    steps:
    - bash: eco Build Dev Job
- stage: QADeploy
  jobs:
    - job: QAJob
      steps:
      - bash: eco Build QA Job
- stage: PRODDeploy
  jobs:
  - job: PRODDeploy
    steps:
    - bash: eco Build PROD Job
